export interface SeedCategory {
  name: string
  slug: string
  description: string
  image: string
  sortOrder: number
  children: Omit<SeedCategory, 'children'>[]
}

export const categories: SeedCategory[] = [
  {
    name: 'Electronics',
    slug: 'electronics',
    description: 'Latest gadgets, devices, and electronic accessories',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400',
    sortOrder: 1,
    children: [
      {
        name: 'Smartphones',
        slug: 'smartphones',
        description: 'Mobile phones and accessories',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=300',
        sortOrder: 1,
      },
      {
        name: 'Laptops',
        slug: 'laptops',
        description: 'Notebooks and ultrabooks',
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=300',
        sortOrder: 2,
      },
      {
        name: 'Audio',
        slug: 'audio',
        description: 'Headphones, speakers, and sound gear',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300',
        sortOrder: 3,
      },
      {
        name: 'Cameras',
        slug: 'cameras',
        description: 'Digital cameras and photography gear',
        image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=300',
        sortOrder: 4,
      },
      {
        name: 'Wearables',
        slug: 'wearables',
        description: 'Smartwatches and fitness trackers',
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300',
        sortOrder: 5,
      },
    ],
  },
  {
    name: 'Clothing',
    slug: 'clothing',
    description: 'Fashion apparel for men, women, and children',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400',
    sortOrder: 2,
    children: [
      {
        name: "Men's Fashion",
        slug: 'mens-fashion',
        description: "Men's clothing and apparel",
        image: 'https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=300',
        sortOrder: 1,
      },
      {
        name: "Women's Fashion",
        slug: 'womens-fashion',
        description: "Women's fashion and style",
        image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=300',
        sortOrder: 2,
      },
      {
        name: "Kids' Fashion",
        slug: 'kids-fashion',
        description: "Children's clothing",
        image: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=300',
        sortOrder: 3,
      },
      {
        name: 'Shoes',
        slug: 'shoes',
        description: 'Footwear for all occasions',
        image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300',
        sortOrder: 4,
      },
    ],
  },
  {
    name: 'Home & Garden',
    slug: 'home-garden',
    description: 'Furniture, decor, garden tools, and home essentials',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400',
    sortOrder: 3,
    children: [
      {
        name: 'Furniture',
        slug: 'furniture',
        description: 'Chairs, tables, sofas, and more',
        image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=300',
        sortOrder: 1,
      },
      {
        name: 'Kitchen',
        slug: 'kitchen',
        description: 'Cookware, appliances, and kitchen tools',
        image: 'https://images.unsplash.com/photo-1556909114-44e3e70034e2?w=300',
        sortOrder: 2,
      },
      {
        name: 'Garden',
        slug: 'garden',
        description: 'Plants, tools, and outdoor living',
        image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=300',
        sortOrder: 3,
      },
      {
        name: 'Lighting',
        slug: 'lighting',
        description: 'Indoor and outdoor lighting solutions',
        image: 'https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=300',
        sortOrder: 4,
      },
      {
        name: 'Bedding',
        slug: 'bedding',
        description: 'Sheets, pillows, and comforters',
        image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=300',
        sortOrder: 5,
      },
    ],
  },
  {
    name: 'Books',
    slug: 'books',
    description: 'Physical and digital books across all genres',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
    sortOrder: 4,
    children: [
      {
        name: 'Fiction',
        slug: 'fiction',
        description: 'Novels, short stories, and literary fiction',
        image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300',
        sortOrder: 1,
      },
      {
        name: 'Non-Fiction',
        slug: 'non-fiction',
        description: 'Biographies, history, and educational',
        image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=300',
        sortOrder: 2,
      },
      {
        name: 'Technical',
        slug: 'technical',
        description: 'Programming, science, and engineering',
        image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=300',
        sortOrder: 3,
      },
      {
        name: "Children's Books",
        slug: 'childrens-books',
        description: 'Books for young readers',
        image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=300',
        sortOrder: 4,
      },
    ],
  },
  {
    name: 'Sports',
    slug: 'sports',
    description: 'Sports equipment, activewear, and outdoor gear',
    image: 'https://images.unsplash.com/photo-1461896836934-bd45ba4d8bfc?w=400',
    sortOrder: 5,
    children: [
      {
        name: 'Fitness',
        slug: 'fitness',
        description: 'Gym equipment and workout gear',
        image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=300',
        sortOrder: 1,
      },
      {
        name: 'Outdoor',
        slug: 'outdoor',
        description: 'Camping, hiking, and adventure',
        image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=300',
        sortOrder: 2,
      },
      {
        name: 'Team Sports',
        slug: 'team-sports',
        description: 'Soccer, basketball, and more',
        image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=300',
        sortOrder: 3,
      },
      {
        name: 'Cycling',
        slug: 'cycling',
        description: 'Bikes, helmets, and cycling accessories',
        image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=300',
        sortOrder: 4,
      },
    ],
  },
  {
    name: 'Beauty',
    slug: 'beauty',
    description: 'Skincare, makeup, and personal care products',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400',
    sortOrder: 6,
    children: [
      {
        name: 'Skincare',
        slug: 'skincare',
        description: 'Cleansers, moisturizers, and serums',
        image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=300',
        sortOrder: 1,
      },
      {
        name: 'Makeup',
        slug: 'makeup',
        description: 'Lipstick, foundation, and more',
        image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=300',
        sortOrder: 2,
      },
      {
        name: 'Haircare',
        slug: 'haircare',
        description: 'Shampoos, conditioners, and styling',
        image: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=300',
        sortOrder: 3,
      },
      {
        name: 'Fragrances',
        slug: 'fragrances',
        description: 'Perfumes and colognes',
        image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=300',
        sortOrder: 4,
      },
    ],
  },
  {
    name: 'Toys',
    slug: 'toys',
    description: 'Toys, games, and entertainment for all ages',
    image: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400',
    sortOrder: 7,
    children: [
      {
        name: 'Board Games',
        slug: 'board-games',
        description: 'Classic and modern board games',
        image: 'https://images.unsplash.com/photo-1611371805429-8b5c1b2c34ba?w=300',
        sortOrder: 1,
      },
      {
        name: 'Action Figures',
        slug: 'action-figures',
        description: 'Collectible figures and playsets',
        image: 'https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?w=300',
        sortOrder: 2,
      },
      {
        name: 'Educational',
        slug: 'educational-toys',
        description: 'Learning toys and STEM kits',
        image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=300',
        sortOrder: 3,
      },
      {
        name: 'Video Games',
        slug: 'video-games',
        description: 'Consoles, games, and accessories',
        image: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=300',
        sortOrder: 4,
      },
    ],
  },
  {
    name: 'Automotive',
    slug: 'automotive',
    description: 'Car parts, accessories, and maintenance products',
    image: 'https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=400',
    sortOrder: 8,
    children: [
      {
        name: 'Car Parts',
        slug: 'car-parts',
        description: 'Replacement and upgrade parts',
        image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=300',
        sortOrder: 1,
      },
      {
        name: 'Car Accessories',
        slug: 'car-accessories',
        description: 'Interior and exterior accessories',
        image: 'https://images.unsplash.com/photo-1530124566582-a45a7e3f3bfe?w=300',
        sortOrder: 2,
      },
      {
        name: 'Automotive Tools',
        slug: 'automotive-tools',
        description: 'Diagnostic and repair tools',
        image: 'https://images.unsplash.com/photo-1619405399517-d7fce0f13302?w=300',
        sortOrder: 3,
      },
    ],
  },
  {
    name: 'Food',
    slug: 'food',
    description: 'Gourmet foods, snacks, and beverages',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
    sortOrder: 9,
    children: [
      {
        name: 'Gourmet',
        slug: 'gourmet',
        description: 'Premium and artisanal foods',
        image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=300',
        sortOrder: 1,
      },
      {
        name: 'Snacks',
        slug: 'snacks',
        description: 'Chips, cookies, and treats',
        image: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=300',
        sortOrder: 2,
      },
      {
        name: 'Beverages',
        slug: 'beverages',
        description: 'Coffee, tea, and specialty drinks',
        image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=300',
        sortOrder: 3,
      },
      {
        name: 'Organic',
        slug: 'organic-food',
        description: 'Organic and natural food products',
        image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=300',
        sortOrder: 4,
      },
    ],
  },
  {
    name: 'Health',
    slug: 'health',
    description: 'Vitamins, supplements, and wellness products',
    image: 'https://images.unsplash.com/photo-1505576399279-0d754c05c542?w=400',
    sortOrder: 10,
    children: [
      {
        name: 'Vitamins',
        slug: 'vitamins',
        description: 'Daily vitamins and supplements',
        image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300',
        sortOrder: 1,
      },
      {
        name: 'Supplements',
        slug: 'supplements',
        description: 'Protein, amino acids, and nutrition',
        image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=300',
        sortOrder: 2,
      },
      {
        name: 'Wellness',
        slug: 'wellness',
        description: 'Mental health and relaxation products',
        image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=300',
        sortOrder: 3,
      },
      {
        name: 'First Aid',
        slug: 'first-aid',
        description: 'Medical supplies and first aid kits',
        image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=300',
        sortOrder: 4,
      },
    ],
  },
]
